name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This is the runner for the build step

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag ghcr.io/harii-2307/npvrus-1.0:latest .

      - name: Debugging info (Build Step)
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Actor: ${{ github.actor }}"

  push:
    needs: build  # This ensures the push step only runs after the build step
    runs-on: ubuntu-latest  # This is the runner for the push step

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token is automatically available

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/harii-2307/npvrus-1.0:latest

      - name: Debugging info (Push Step)
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Actor: ${{ github.actor }}"

