name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/harii-2307/npvrus-1.0:latest .

      - name: Save image as artifact
        run: docker save ghcr.io/harii-2307/npvrus-1.0:latest -o image.tar

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: image.tar

  push:
    name: Push Docker Image to GHCR
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/harii-2307/npvrus-1.0:latest
